# Generated by Django 4.0.2 on 2023-01-07 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_quesmodel_remove_question_user_delete_choice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuesModel',
            new_name='Question',
        ),
    ]
