# Generated by Django 4.0.2 on 2023-01-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_quesmodel_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='questions',
        ),
    ]
